기본 spring app & react 구조 추가
Azure-Samples/gh-codespaces-copilot-in-a-day-ko pull request #2
Opened 2023-04-18 21:41 UTC by n-y-kim

## Purpose

* Backend spring & Frontend react 기본 구조 추가

## Does this introduce a breaking change?

```
[ x ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
run/debug java
npm start
```

* Test the code

```
curl http://localhost:3000/hello
> Test React with Spring Boot!
```

## What to Check
Verify that the following are valid
* Codespace에서 `npm start` script 못 찾는 현상 발생

## Other Information

2023-04-20 04:01 UTC, justinyoo requested changes
전체적인 디렉토리 구조를 조정해 보시겠습니까?

2023-04-21 02:26 UTC, justinyoo requested changes
리드미 파일 업데이트 부탁해욥

2023-04-21 02:26 UTC, justinyoo commented on README.md
> +3. 브라우저에서 http://localhost:3000/ 접속
우리는 코드스페이스 기준이니까 `http://localhost:3000` 이라고 접속할 수 없으니, 우측 하단에 팝업 뜨는 걸 스샷을 따서 보여주면 어때요?

2023-04-21 02:26 UTC, justinyoo commented on README.md
> +### 스프링 앱 로컬 테스트
로컬 테스트라기 보다는 로컬 실행 쯤이 더 맞을 듯?

2023-04-21 09:18 UTC, n-y-kim commented on README.md
> +3. 브라우저에서 http://localhost:3000/ 접속
[2c3b675](https://github.com/Azure-Samples/gh-codespaces-copilot-in-a-day-ko/pull/2/commits/2c3b6754019e6d2d42fc7c2d8e2bee3c74a8ff5a)

2023-04-21 09:18 UTC, n-y-kim commented on README.md
> +### 스프링 앱 로컬 테스트
[2c3b675](https://github.com/Azure-Samples/gh-codespaces-copilot-in-a-day-ko/pull/2/commits/2c3b6754019e6d2d42fc7c2d8e2bee3c74a8ff5a)

2023-04-21 09:20 UTC, n-y-kim commented
.mvn 복구해뒀습니다

2023-04-21 13:39 UTC, justinyoo approved these changes
LGTM 수고하셨습니다!

2023-04-21 13:39 UTC, merged