프론트엔드 first draft
Azure-Samples/gh-codespaces-copilot-in-a-day-ko pull request #3
Opened 2023-04-23 21:03 UTC by n-y-kim

## Purpose

* Chat 기능 UI 구현 - 백엔드 미완성. Test용 POST만 완성된 상태

> <img width="1143" alt="Screenshot 2023-04-24 at 1 30 22 AM" src="https://user-images.githubusercontent.com/76769919/233852176-ca8fe46d-2ccf-4278-8077-45f480b882f0.png">

## Does this introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
cd web
npm install
npm start

cd api
mvn spring-boot:run
```

* Test the code

```
메세지 보냈을 때 애저봇 답변 Hello, {내가보낸메세지}! 확인
```

## What to Check
Verify that the following are valid
* 답변 생성 시 scroll down 되는 것 확인
* Sync branch 후에도 **그 전에 merge한 커밋들이 새로운 커밋으로 잡혔습니다. 요거 때문에 merge 문제가 없으려나** 모르곘네요.

## Other Information

* 업데이트 필요한 UI: 애저봇 답변에 대한 scroll down이 안됨 & 반응이 늦음.
* 추가로 구현해야 하는 UI: 기록 Create, Read 용 sidebar
* 전반적인 UI 피드백 부탁드립니다

2023-04-24 00:39 UTC, justinyoo requested changes
UI는 우선 그정도면 충분할 듯 싶구요, 몇가지 아키텍처 관점에서 CORS 적용 여부, 보안 관련 여부 코멘트 남겨뒀습니다.

2023-04-24 00:39 UTC, justinyoo commented on api/.gitignore
> +!api/src/main/resources/application.properties
혹시 이 파일은 빌드할 때 자동으로 만들어지는 건가요? 만약 아니라면, `api/src/main/resources/application.sample.properties` 같은 파일을 하나 만들어서 그 파일을 참조하라고 안내를 해야 할 것 같습니다.

2023-04-24 00:39 UTC, justinyoo commented on api/src/main/java/roadshow/demo/api/controller/MessageController.java
> +@CrossOrigin(origins = "http://localhost:3000")
세가지 질문이 있습니다.

1. CORS 적용할 때, 이렇게 로컬호스트로 하드코딩하면, 나중에 배포할 때에는 문제가 되지 않을까요?
2. 지금 우리 아키텍처는 프론트엔드와 백엔드가 직접 커뮤니케이션하는 것이 아니라 중간에 APIM이 끼는데요, 이 경우에는 CORS를 여기에 적용시키는 것이 맞나요?
3. 근본적으로 CORS 적용이 필요한가요? CORS 적용하지 않고 직접 API를 호출한다면 어떻게 되나요?

2023-04-24 00:39 UTC, justinyoo commented on web/src/App.js
> +    fetch("http://localhost:8080/api/messages", {
1. 이렇게 호출하면 굳이 앞에서 CORS 설정을 안해도 되지 않을까요?
2. 로컬호스트로 하드코딩하는 대신 이 부분을 환경설정 값으로 받아올 수 있게끔 바꿔보는 것이 좋겠습니다.

2023-04-24 00:39 UTC, justinyoo commented on api/src/main/java/roadshow/demo/api/controller/MessageController.java
> +        String result = "Hello, " + text + "!";
혹시 AOAI API 포맷이 이거 맞나요? 아직 AOAI 적용 안한 것 맞죠?

2023-04-24 13:34 UTC, n-y-kim commented on api/src/main/java/roadshow/demo/api/controller/MessageController.java
> +        String result = "Hello, " + text + "!";
적용 안 된 것 맞습니다! 프론트 PR 한 번 하고 새로 PR 만들려고 했습니다.

2023-04-25 12:44 UTC, n-y-kim commented on api/src/main/java/roadshow/demo/api/controller/MessageController.java
> +        String result = "Hello, " + text + "!";
https://github.com/Azure-Samples/gh-codespaces-copilot-in-a-day-ko/pull/3/commits/b090df41e7f8c00fd250d6418b452c1771cbc51a

2023-04-25 16:49 UTC, justinyoo approved these changes
우선 로컬 테스트용이라고 생각하고 머지하겠습니다. 다만, localhost 라고 하드코딩한 부분이 코드스페이스 안에서 제대로 작동할지는 모르겠네요. 이 부분은 적어도 코드스페이스용으로라도 변경해야 할 듯 합니다.

2023-04-25 16:50 UTC, merged